---
title: "salmon_data"
output: html_document
---

```{r}
library(ggplot2)
library(dplyr)
library(tidyr)

```


```{r}
Salmon <- read.csv("../data/Catch_Escapement_Alaska_Fish274.csv")
```


```{r}
esc <- read.csv("../data/Escapement_Fish274.csv")
ret <- read.csv("../data/Total_Return_Fish274.csv")
```

```{r}
esc_long <- esc %>%
  pivot_longer(cols = c(2:10))
```


```{r}
ret_long <- ret %>%
  pivot_longer(cols = c(2:10))
```

```{r}
ggplot(ret_long , aes(x = year, y = value, color = name)) +
  geom_line()
```

```{r}
ggplot(esc_long , aes(x = Year, y = value, color = name)) +
  geom_line()
```

```{r}
ggplot() + 
geom_line(data=esc_long, aes(x = Year, y = value, color = name), linetype="dotted") + 
geom_line(data=ret_long, aes(x = year, y = value, color = name))
```

```{r}
ggplot() + 
geom_line(data=esc_long, aes(x = Year, y = value), linetype="dotted") + 
geom_line(data=ret_long, aes(x = year, y = value)) +
facet_wrap(~name)
```

```{r}
ggplot() +
  geom_point(data=esc_long, aes(Year, value, color= name)) +
  geom_point(data=ret_long, aes(year, value, color= name))
```
```{r}
ggplot(data = Salmon, aes(Year, Population)) +
  geom_point(data=esc_long, aes(Year, value), color = 'blue', size = 0.1) +
  geom_point(data=ret_long, aes(year, value), color = 'black', size = 0.1) +
  facet_wrap(~name)
```
joining

```{r}
esc_ret <- left_join(esc_long, ret_long, by=c('Year'='year', 'name'='name'))
```


```{r}
ggplot() +
  geom_point(data = esc_ret, aes(x = esc, y = ret)) +
  facet_wrap(~name)
```

